"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from ast import Pass
from pathlib import Path
from mongoengine import connect
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from datetime import timedelta


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$#-9^rd$0b!8ftz+d4w2lz%p2)4vn7t0z0%q!2qucl_03k&*9&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



INSTALLED_APPS = [
	'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# tech 
	'corsheaders',
	'rest_framework',
	'rest_framework_simplejwt',
# apps
	'account',
	'me_chat',	
	'groups_chat'
]

AUTH_USER_MODEL = 'account.User'

MONGODB_SETTINGS = {
    'db': 'chat_application',
    'host': 'localhost',
    'port': 27017,
	'LINK':"mongodb://localhost:27017/",
	
}
# redis://default:hOobdpZfMzVbRUCKDUjfmTERDeOgzltX@yamabiko.proxy.rlwy.net:40088  
REDIS_SETTINGS = {
	'REDIS_IP' : "192.168.56.101",
	'REDIS_PORT':6379,
	'REDIS_ONLINE_IP': 'yamabiko.proxy.rlwy.net', #'redis-13101.c8.us-east-1-3.ec2.redns.redis-cloud.com',
	'REDIS_ONLINE_PORT': 40088,#13101,
	'DB_FOR_CHATS' : '0',
	'DB_FOR_CACHE' : '1',
	'PASSWORD':'redispass',
	'ONLINE_PASS':'hOobdpZfMzVbRUCKDUjfmTERDeOgzltX',#O9dAgc2IuZC2qTvXrqGBzg9R9p2gGKyI'
}

ONLINE_REDIS=True
SAVE_MESSAGES = True


connect(MONGODB_SETTINGS['db'], host=f'mongodb://localhost:27017/{MONGODB_SETTINGS['db']}')


CORS_ALLOWED_ORIGINS=['http://localhost:5173','https://36f1-103-182-166-208.ngrok-free.app','http://192.168.253.21:5173']
CORS_ALLOW_CREDENTIALS = True 
CSRF_COOKIE_SECURE = False  
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
#CSRF_COOKIE_SAMESITE = "None"

CSRF_TRUSTED_ORIGINS = [
	'https://c506-103-182-166-208.ngrok-free.app',
	'http://192.168.142.21:5173'

]
LOGIN_URL = '/admin/'
LOGIN_REDIRECT_URL = '/'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
}


MIDDLEWARE = [
	
	'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'



if ONLINE_REDIS:
	HOST_REDIS =f'redis://default:{REDIS_SETTINGS['ONLINE_PASS']}@{REDIS_SETTINGS['REDIS_ONLINE_IP']}:{REDIS_SETTINGS['REDIS_ONLINE_PORT']}'
else:
	HOST_REDIS =f'redis://{REDIS_SETTINGS['REDIS_IP']}:{REDIS_SETTINGS['REDIS_PORT']}/{REDIS_SETTINGS['DB_FOR_CACHE']}'

CHANNEL_LAYERS = {
		# 'default': {
		# 	'BACKEND':"channels.layers.InMemoryChannelLayer",  
		# },
		"default": {
			"BACKEND": "channels_redis.core.RedisChannelLayer",
			"CONFIG": {
			"hosts": [(HOST_REDIS)],
			 "prefix": "me_chat_",
			},
		},
	}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
